import 'package:flutter/material.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox2widget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox2widget/generated/GeneratedOPENNNNEW1Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox2widget/generated/GeneratedWehavecreatedaflexiblesolutionforthemanagementofshiftsb.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox2widget/generated/GeneratedContinueWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox2widget/generated/GeneratedWelcomeToOpenHeartRecruitmentacareerManagerFocusAppWidg.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox2widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox2widget/generated/GeneratedTopbarWidget1.dart';

/* Frame iPhone 11 Pro / X - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -9.0,
                top: -68.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 585.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: -9.0,
                top: -38.0,
                right: null,
                bottom: null,
                width: 467.0,
                height: 555.0,
                child: GeneratedOPENNNNEW1Widget(),
              ),
              Positioned(
                left: 111.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 40.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 140.0,
                top: 736.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 33.0,
                child: GeneratedContinueWidget(),
              ),
              Positioned(
                left: 3.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 16.0,
                child: GeneratedTopbarWidget1(),
              ),
              Positioned(
                left: 34.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 114.0,
                child:
                    GeneratedWelcomeToOpenHeartRecruitmentacareerManagerFocusAppWidg(),
              ),
              Positioned(
                left: 69.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 88.0,
                child:
                    GeneratedWehavecreatedaflexiblesolutionforthemanagementofshiftsb(),
              )
            ]),
      ),
    ));
  }
}
