import 'package:flutter/material.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox4widget/generated/GeneratedTopbarWidget3.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox4widget/generated/GeneratedLogInWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox4widget/generated/GeneratedAlreadyAMemberWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox4widget/generated/GeneratedZzzzzzz1Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox4widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox4widget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox4widget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox4widget/generated/GeneratedWhyWouldManagersCarersConsiderUsAsPrimeOptionsWidget.dart';

/* Frame iPhone 11 Pro / X - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -9.0,
                top: -72.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 609.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: -120.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 553.0,
                height: 576.0,
                child: GeneratedZzzzzzz1Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 16.0,
                child: GeneratedTopbarWidget3(),
              ),
              Positioned(
                left: 5.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 404.0,
                height: 46.0,
                child:
                    GeneratedWhyWouldManagersCarersConsiderUsAsPrimeOptionsWidget(),
              ),
              Positioned(
                left: 101.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 40.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 258.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 18.0,
                child: GeneratedLogInWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 18.0,
                child: GeneratedAlreadyAMemberWidget(),
              ),
              Positioned(
                left: 157.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 26.0,
                child: GeneratedSignUpWidget(),
              )
            ]),
      ),
    ));
  }
}
