import 'package:flutter/material.dart';

/* Text Managers see us as a Reliable Stand-by Professional-staff-option and are saved from the stress of sourcing for staffs. Carers on their own makes their own Rota & Maneges their own Rota & Manage their Own Time
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagersseeusasaReliableStandbyProfessionalstaffoptiona
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Align(
      alignment: Alignment.bottomCenter,
      child: Text(
        '''Managers see us  as a Reliable Stand-by
Professional-staff-option and are saved
from the stress of sourcing for
staffs.
Carers on their own makes their own Rota & Maneges
their own Rota & Manage their Own Time''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.2202272415161133,
          fontSize: 13.0,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: -0.26, */
        ),
      ),
    ));
  }
}
