import 'package:flutter/material.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox6widget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox6widget/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox6widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox6widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox6widget/generated/GeneratedTopbarWidget6.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox6widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox6widget/generated/GeneratedVerificationDocumentationsWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox6widget/generated/GeneratedDdddddddddddddddd1Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox6widget/generated/GeneratedRectangle9Widget1.dart';

/* Frame iPhone 11 Pro / X - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1014.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1014.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 370.0,
                              height: 16.0,
                              child: GeneratedTopbarWidget6(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: -264.0,
                              right: null,
                              bottom: null,
                              width: 393.0,
                              height: 569.0,
                              child: GeneratedRectangle6Widget3(),
                            ),
                            Positioned(
                              left: -92.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 240.0,
                              child: GeneratedDdddddddddddddddd1Widget(),
                            ),
                            Positioned(
                              left: 144.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 173.0,
                              height: 57.0,
                              child:
                                  GeneratedVerificationDocumentationsWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 329.0,
                              height: 70.0,
                              child: GeneratedRectangle8Widget1(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 329.0,
                              height: 70.0,
                              child: GeneratedRectangle9Widget1(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 329.0,
                              height: 70.0,
                              child: GeneratedRectangle12Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 617.0,
                              right: null,
                              bottom: null,
                              width: 329.0,
                              height: 70.0,
                              child: GeneratedRectangle11Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 437.0,
                              right: null,
                              bottom: null,
                              width: 329.0,
                              height: 70.0,
                              child: GeneratedRectangle10Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
