import 'package:flutter/material.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox3widget/generated/GeneratedContinueWidget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox3widget/generated/GeneratedOPENHEARTT55551Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox3widget/generated/GeneratedWhatIsItAboutOpenHeartAppWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox3widget/generated/GeneratedWehavecreatedaflexiblesolutionforthemanagementofshiftsb1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox3widget/generated/GeneratedTopbarWidget2.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox3widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox3widget/generated/GeneratedRectangle4Widget.dart';

/* Frame iPhone 11 Pro / X - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -18.0,
                top: -70.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 609.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: -42.0,
                top: -29.0,
                right: null,
                bottom: null,
                width: 584.0,
                height: 503.0,
                child: GeneratedOPENHEARTT55551Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 114.0,
                child: GeneratedWhatIsItAboutOpenHeartAppWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 88.0,
                child:
                    GeneratedWehavecreatedaflexiblesolutionforthemanagementofshiftsb1(),
              ),
              Positioned(
                left: 105.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 40.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 133.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 33.0,
                child: GeneratedContinueWidget1(),
              ),
              Positioned(
                left: 5.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 16.0,
                child: GeneratedTopbarWidget2(),
              )
            ]),
      ),
    ));
  }
}
