import 'package:flutter/material.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox7widget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox7widget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox7widget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox7widget/generated/GeneratedRectangle5Widget3.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox7widget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox7widget/generated/GeneratedTopbarWidget5.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox7widget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox7widget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox7widget/generated/GeneratedRectangle7Widget1.dart';

/* Frame iPhone 11 Pro / X - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 75, 30, 206),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 378.0,
                height: 735.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 38.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 33.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedRectangle5Widget3(),
              ),
              Positioned(
                left: 8.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 16.0,
                child: GeneratedTopbarWidget5(),
              ),
              Positioned(
                left: 37.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 33.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 104.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 40.0,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 123.0,
                top: -5.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 149.0,
                child: GeneratedGroup2Widget1(),
              ),
              Positioned(
                left: 158.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 33.0,
                child: GeneratedLOGINWidget(),
              )
            ]),
      ),
    ));
  }
}
