import 'package:flutter/material.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedTopbarWidget4.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedTestWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedSubmitWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox5widget/generated/GeneratedMobileNoWidget.dart';

/* Frame iPhone 11 Pro / X - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 75, 30, 206),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 378.0,
                height: 812.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 33.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 33.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 8.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 16.0,
                child: GeneratedTopbarWidget4(),
              ),
              Positioned(
                left: 37.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 33.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 45.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 30.0,
                child: GeneratedConfirmPasswordWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 30.0,
                child: GeneratedMobileNoWidget(),
              ),
              Positioned(
                left: 99.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 40.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 99.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 40.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 692.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 40.0,
                child: GeneratedSubmitWidget(),
              ),
              Positioned(
                left: 165.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 40.0,
                child: GeneratedTestWidget(),
              ),
              Positioned(
                left: 123.0,
                top: -5.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 149.0,
                child: GeneratedGroup2Widget(),
              )
            ]),
      ),
    ));
  }
}
