import 'package:flutter/material.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox1widget/generated/GeneratedWELCOMETOOPENHEARTWidget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox1widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox1widget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/recruitment_20appapp/generatediphone11prox1widget/generated/GeneratedTopbarWidget.dart';

/* Frame iPhone 11 Pro / X - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 75, 30, 206),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 16.0,
                child: GeneratedTopbarWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 382.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 29.0,
                child: GeneratedWELCOMETOOPENHEARTWidget(),
              ),
              Positioned(
                left: 72.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedFrame1Widget(),
              )
            ]),
      ),
    ));
  }
}
