import 'package:flutter/material.dart';

/* Rectangle cccccccccccccccccccccc 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCccccccccccccccccccccc1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 317.0,
      height: 204.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/d5b0691de525bbe80926fe3867588a71cb6bc767.png",
          color: null,
          fit: BoxFit.cover,
          width: 317.0,
          height: 204.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
